#!/bin/bash

if [ $1 ]; then
  case $1 in
    install)
      apm install --packages-file package-list ;;
    save)
      rm package-list ;
      apm list --installed --bare > package-list ;;
  esac
fi
